### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by mschae16** [GreyMatteOr/mod_0_skills#1]
@GreyMatteOr - Excellent work on this assessment! You are officially `technical ready`! Your class and instance examples were thorough and contextually sound, and I can see you have a clear understanding of variable assignment and data types.

Some highlights that jumped out to me are:

- Great to see your usage of camelCase in variable, method, and attribute naming throughout.
- Your naming conventions are on point! One of your boolean attributes was `isOccupied` which to me very clearly signifies a true or false value.  Great method naming as well - all in the present imperative tense.

**Comment by GreyMatteOr** [comment]
@mschae16 Woo hoo!!
